name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  update-ec2:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Deploy to EC2
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
        EC2_HOST: ${{ secrets.EC2_HOST }}
        EC2_USER: ${{ secrets.EC2_USER }}
      run: |
        set -e
        echo "$SSH_PRIVATE_KEY" > private_key.pem
        chmod 600 private_key.pem
        
        # Check SSH connection
        echo "Checking SSH connection..."
        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST 'echo "SSH connection successful"'
        
        # Pull latest code and install dependencies
        echo "Pulling latest code and installing dependencies..."
        ssh -o StrictHostKeyChecking=no -i private_key.pem $EC2_USER@$EC2_HOST "
          cd /var/www/Elite-Mediator
          sudo git pull origin main
          
          cd /var/www/Elite-Mediator/client
          sudo npm install
          
          cd /var/www/Elite-Mediator/server
          sudo npm install
          
          sudo pm2 restart all
          sudo systemctl reload nginx
        "

        echo "Deployment finished."
        rm -f private_key.pem
